### ISSUE TITLE
eth.blockNumber is 0 while syncing

### ISSUE THREAD

**Issue by osizadmin** [binance-chain/bsc#140]
BSC version: Geth/v1.0.7-f1d92bef/linux-amd64/go1.15.5
OS & Version: ubuntu 18.04 AWS EC2 instance with SSD hard disk
Started with: geth_linux --config config.toml --datadir node 

> eth.syncing;
{
  currentBlock: 6410169,
  highestBlock: 6410235,
  knownStates: 89723794,
  pulledStates: 89683710,
  startingBlock: 6410107
}
> eth.blockNumber;
0

**Comment by erickcrus** [comment]
Mine too, think i'ts default. I'm syncing for 7 days already.
> eth.syncing
{
  currentBlock: 6418490,
  highestBlock: 6418559,
  knownStates: 333671898,
  pulledStates: 333670169,
  startingBlock: 6363042
}

**Comment by a04512** [comment]
mine 3days
{'currentBlock': 6420184,
 'highestBlock': 6420280,
 'knownStates': 197201667,
 'pulledStates': 197199634,
 'startingBlock': 6419419}

**Comment by dsbaars** [comment]
This is normal behaviour, it should show the correct number after it correctly syncs fully. Make sure you use a fast SSD, traditional HDDs are too slow to become in sync.

**Comment by erickcrus** [comment]
@dsbaars Do you know how many knownStates it is now?

**Comment by dsbaars** [comment]
That is only relevant when synchronising and specific to your own situation. See [the answer of this StackOverflow question](https://ethereum.stackexchange.com/questions/9112/what-is-knownstates/9116).

**Comment by osizadmin** [comment]
@dsbaars Yes we have used SSD hard disk from AWS and vultr cloud instances.

**Comment by dsbaars** [comment]
I believed you without the screenshot, this is not an issue since it is normal behaviour like I already mentioned. When `eth.syncing` shows it is lagging a bit behind, it is almost synchronized. Be patient, do not restart the geth client since that only delays it because of necessary initialisations. 

You don't mention your EC2 instance type, if you have an instance with 16GB ram+ you could try increasing cache size to make it sync faster.

**Comment by osizadmin** [comment]
@dsbaars 

We have using m5.xlarge EC2 instance with 500GB SSD hard disk. We are waiting for last one week. Still its showing this kind of information from the server. 

Our exchange users are waiting to use this BEP20 tokens. we are losing our users for this kind issue in last one week.

Kindly advise us how to resolve this issue ASAP.

**Comment by dsbaars** [comment]
- This issue tracker is not blockchain / binance smart chain support. I am not a developer of this project, nor related to Binance in any way.  Just a user like you. 
- I am sorry to hear you have trouble getting in sync but the issue you opened is not an issue.
- The blockchain size grew a lot since last February, 500 GB SSD is not sufficient anymore. The [minimum requirements](https://docs.binance.org/smart-chain/developer/fullnode.html) were recently updated to reflect that.
- Your users are free to use any other public BSC node, that is the big advantage of a blockchain. If your clients really rely on this single node in my personal opinion there is a big design flaw in your application.

**Comment by osizadmin** [comment]
still now block number not syncing. block number showing 0.

**Comment by dsbaars** [comment]
4th time, this is correct behaviour when it's not fully synced. Please close this issue.

**Comment by osizadmin** [comment]
How to resolve this issue.

**Comment by dsbaars** [comment]
Not an issue.

**Comment by erickcrus** [comment]
2 weeks here:

  currentBlock: 6712958,
  highestBlock: 6713075,
  knownStates: 485704977,
  pulledStates: 485704072,
  startingBlock: 6538481

**Comment by 1b1og-com** [comment]
alway this
> eth.syncing
{
  currentBlock: 6784288,
  highestBlock: 6784407,
  knownStates: 133873248,
  pulledStates: 133865063,
  startingBlock: 6783739
}
> eth.blockNumber
0

**Comment by osizadmin** [comment]
Hello Team,

Could find any solution for this issues.

**Comment by wowgeeker** [comment]
Anyone can tell me the current upper bound for knownStates?
Secrets to success:  2000 max peers + ssd (LOCAL SSD if you use cloud servers) 

1 day here:
`> eth.syncing
{
  currentBlock: 7101308,
  highestBlock: 7101373,
  knownStates: 183473180,
  pulledStates: 183473179,
  startingBlock: 0
}`

**Comment by guagualvcha** [comment]
for the node syncing issue, please check the pinned two issues and find the best practice.
