### ISSUE TITLE
No new peers added in 24 hours

### ISSUE THREAD

**Issue by algobotishere** [binance-chain/bsc#201]
Node's admin.peers.length in between 23-24, 

- Port 30311 opened for all incoming connections
- Cache size 32GB
- Geth version upgrade_1.10.2
- Maxpeers in config.toml set to 2000

As @bellsovery posted, they connected to 998 peers. What I am doing wrong? 

https://github.com/binance-chain/bsc/issues/189#issuecomment-836459196

Offtop: can someone share enode list of full bsc nodes?

**Comment by APshenkin** [comment]
Same thing, Run new node with fast sync. 30311 is opened. But 0 peers

**Comment by smartins** [comment]
@algobotishere have you called `geth --datadir node init genesis.json` ?

**Comment by APshenkin** [comment]
Issue solved (I used wrong networkId in config.toml)

**Comment by yoongyy** [comment]
I also having the same issue, I guess many of the nodes still using the old version of Geth so it is not compatible with the newer version, so it will drop those older nodes. That means only less than 200 nodes using the latest version of Geth. This is not good if they didn't upgrade to the new version, the new GUYS like us will get poor syncing performance, although if your using 16 vCPU, 128GB Ram also useless, because only few peers connected to you...

I hope this can be solved like forcing the old nodes to upgrade to the newer version or something.

**Comment by KeefeL** [comment]
> I also having the same issue, I guess many of the nodes still using the old version of Geth so it is not compatible with the newer version, so it will drop those older nodes. That means only less than 200 nodes using the latest version of Geth. This is not good if they didn't upgrade to the new version, the new GUYS like us will get poor syncing performance, although if your using 16 vCPU, 128GB Ram also useless, because only few peers connected to you...
> 
> I hope this can be solved like forcing the old nodes to upgrade to the newer version or something.

I think peers number is not related with binary version, in case there are some bug and performance issue, you are recommended to upgrade your version.

**Comment by KeefeL** [comment]
We have responded to the question and will proceed to close the case as we didn't get any additional question after 3days. 
Please proceed to join our Discord channel for more discussion at https://discord.com/invite/YPDsUqcwR8
