### ISSUE TITLE
Abigen doesn't work for BUSD

### ISSUE THREAD

**Issue by jon4hz** [binance-chain/bsc#241]
#### System information

Abigen version: 1.10.3
OS & Version: Linux

#### Expected behaviour
Executing `abigen --abi=busd_abi.json --pkg=busd` should return a valid go package to interact with the contract.

#### Actual behaviour
When I try to compile the contract ABI for BUSD to generate a golang package to use it in an application, I always get the error `Fatal: Failed to generate ABI binding: duplicated identifier "decimals"(normalized "Decimals"), use --alias for renaming`. After that error, I ran `abigen --abi=busd_abi.json --pkg=busd --alias decimals=Decimals` but I still got the same error.

#### Steps to reproduce the behaviour

1. copy the contract ABI from [here](https://bscscan.com/address/0xe9e7cea3dedca5984780bafc599bd69add087d56#code) and save it in the file "busd_abi.json"
2. execute `abigen --abi=busd_abi.json --pkg=busd --alias decimals=Decimals`

**Comment by jon4hz** [comment]
Actually `abigen` doesn't seem to work with any Binance-Peg token. Other BEP20 tokens like cake work like a charm.

**Comment by marcello33** [comment]
Any news on this?

**Comment by jon4hz** [comment]
Sadly not

**Comment by DefiDebauchery** [comment]
`abigen` turns attribute and method names into [Upper]CamelCase (also known as PascalCase).  My Solidity is shaky, so I'm not entirely sure why the variables are getting treated as methods; maybe because they're not specified as internal, making them a view?

In any case, it also has a way of remapping multiple methods at once using comma-separated arguments for `--alias`. I was able to get some output by renaming the internal variable names. I'm hoping it's the output you're expecting.
```bash
abigen --abi=busd_abi.json --pkg=busd --alias _symbol=privateSymbol,_name=privateName,_decimals=privateDecimals
```

Research Sources:
https://github.com/miguelmota/ethereum-development-with-go-book/issues/56
https://github.com/ethereum/go-ethereum/blob/master/cmd/abigen/main.go#L248
