### ISSUE TITLE
So.. up to now, approximatively。。。。how many is the known state if fully synced?

### ISSUE THREAD

**Issue by gongyaodon** [binance-chain/bsc#245]

**Comment by n8twj** [comment]
I have a node that has been syncing for a week now: 

> eth.syncing
{
  currentBlock: 7677152,
  highestBlock: 7677221,
  knownStates: 680899667,
  pulledStates: 680825447,
  startingBlock: 7627578
}

**Comment by gongyaodon** [comment]
> I have a node that has been syncing for a week now:
> 
> > eth.syncing
> > {
> > currentBlock: 7677152,
> > highestBlock: 7677221,
> > knownStates: 680899667,
> > pulledStates: 680825447,
> > startingBlock: 7627578
> > }

So horrible, we run a node only 44****** states synced by far.
what exactly KNOWN STATES is...  so huge,  tons of sh*t ???

**Comment by skyh24** [comment]
eth.syncing
{
  currentBlock: 7679300,
  highestBlock: 7679375,
  knownStates: 744673926,
  pulledStates: 744557060,
  startingBlock: 7511148
}

1.1.0 still not finish!

**Comment by gongyaodon** [comment]
@guagualvcha , President Gua, Is there any solutions?

**Comment by CryptoVader** [comment]
Somebody knows how many knownStates are required to be fully sync ?

**Comment by urkishan** [comment]
As I am also facing this, as my blocks always showing 100 behind.
```
{
  currentBlock: 7738573,
  highestBlock: 7738689,
  knownStates: 370745564,
  pulledStates: 370690961,
  startingBlock: 7716912
}
```

**Comment by zhongfu** [comment]
the number of `knownStates` in `eth.syncing` is **not representative of sync progress** if your storage can't keep up (e.g. low iops)

a node that can keep up should finish a fast sync at approximately 300M or so `knownStates`

if you're seeing a ridiculously high number of `knownStates` (>400M as a rough ballpark?), then it's quite possible that your node:
- has poor disk read/write i/o performance,
- is struggling to download all the state entries fast enough before the pivot shifts, **and**
- will likely never finish syncing unless you change something

I had a similar issue when I first attempted to run a BSC node; in my case, it was because I was using zfs. Not sure why -- maybe it's the large record size, or the fact that it's a CoW fs. Switching to xfs allowed all of my nodes to complete a fast sync in less than 10h

If you're on a VPS or some other cloud service, make sure you're able to get enough IOPS. Your provider might be:
- limiting disk IOPS (e.g. Amazon)
- oversubscribing their SSDs (e.g. 50 VPSes, all doing io-intensive things, on a single SSD)
- provisioning crap storage for your VPS/instance

**Comment by urkishan** [comment]
Related to https://github.com/binance-chain/bsc/issues/258

**Comment by ravinayag** [comment]
My node running on m5zn.2xlarge AWS instance and last few days. I still get the variance around 80 blocks and sometimes jump to 120 blocks
I have separate nvme 1TB  gp3 with 16k IOPS & 150Mb/s

> eth.syncing
{
  currentBlock: 8126606,
  highestBlock: 8126726,
  knownStates: 756777931,
  pulledStates: 756751364,
  startingBlock: 8116319
}

> eth.syncing.highestBlock - eth.syncing.currentBlock
123

why this average variance? is it an expected result?

**Comment by zhongfu** [comment]
@ravinayag 
> > knownStates: 756777931,
> > pulledStates: 756751364,

Seems like your node isn't able to sync state entries fast enough. You should be seeing no more than ~300-350M states by the end of the sync if your node is able to keep up.

What's happening is that:
- it selects a block height slightly (~100 blocks?) before the latest known block height as the pivot (currentBlock)
- it downloads all the state trie nodes it can (for the state trie at the current pivot), until the pivot becomes stale (too far away from highestBlock)
- rinse and repeat until it gets *at least* all of the state trie nodes for the state trie at the current pivot is downloaded
- then, switch into full sync mode to download and execute the remaining blocks

Not sure, though -- seems like someone in #258 was able to sync properly with a 1TB gp3 EBS volume. Perhaps it's got something to do with instance configuration, e.g. filesystem?

**Comment by ravinayag** [comment]
@zhongfu 
Thanks for the detailed info. 
will ZFS is recommended FS due to the large number of files created on the node sync. ?

Ref :  [ext4 vs zfs ](https://www.phoronix.com/scan.php?page=article&item=ubuntu1910-ext4-zfs&num=2)
considering the factor from the above article,  Seq read, no. of files......

Have anybody tried with xfs ..?
``` 
$  ls -l node/geth/chaindata | wc -l
232973

$ du -sh 7544969.ldb
2.1M    7544969.ldb

```

**Comment by zhongfu** [comment]
@ravinayag I'm using xfs on all of my nodes.

I haven't had a great experience with ZFS -- my guess is that it's got something to do with the `recordsize` of the dataset that I kept the chaindata in.

I've yet to try ext4, but I reckon it should be alright as well.

```
$ find chaindata/ | wc -l
75539

$ find chaindata/ -name "*.ldb" | tail -n 1
chaindata/3214003.ldb
```

**Comment by ravinayag** [comment]
I created with fresh sync with new xfs fs., i think it's able to get sync to the nearest blocks(~90) in 8 hours. but my initial question is still intact. because this time i had 30k iops with io2 volume type and xfs fs.  and the output for ref. and  followed the  [guide](https://docs.binance.org/smart-chain/developer/fullnode.html) as per bsc full node sync.
```
$ find chaindata/ -name "*.ldb" | tail -n 1
chaindata/142683.ldb
$ find chaindata/ | wc -l
27836
eth.syncing
{
  currentBlock: 8149261,
  highestBlock: 8149369,
  knownStates: 191332221,
  pulledStates: 191264220,
  startingBlock: 0
}
eth.syncing.highestBlock - eth.syncing.currentBlock
123
eth.syncing.knownStates - eth.syncing.pulledStates
49569
```
I'm really worried now,  what is next......
Do I need to finger cross for the next few hours and see the results or I still have a chance to try with......options to get the full sync node... ?

**Comment by zhongfu** [comment]
@ravinayag might be worth waiting a bit more -- you should be seeing at least 290k knownStates, I think

**Comment by ravinayag** [comment]
@zhongfu , Thank you for your inputs. 
Finally, it got sync fully and i got "NaN " from eth.syncing, and this time I see the Instance memory(32g) was fully occupied.

**Comment by amitOodles** [comment]
@zhongfu  @ravinayag 
i am syncing my mainnet bsc node for 4 days and this is the latest syncing status

![image_2021_07_27T07_57_09_708Z](https://user-images.githubusercontent.com/20085459/127120099-007be0e3-04f5-4c0b-bcb7-59db30826ae2.png)

Also the IOPS details are given in this image

![image_2021_07_27T07_58_09_988Z](https://user-images.githubusercontent.com/20085459/127120218-6c20058e-8981-46bf-befb-6c5a5ac760ea.png)

The IOPS limit is 5000, but the I/O taking place is below the limit and the node is not getting synced. What can be the issue with the I/O usage ?

**Comment by guagualvcha** [comment]
FYI https://github.com/binance-chain/bsc/issues/104
