### ISSUE TITLE
How to import binance-chain/bsc?

### ISSUE THREAD

**Issue by frankli-dev** [binance-chain/bsc#246]
The module name of this repo is `module github.com/ethereum/go-ethereum`
When I try to add this as dependency with the following, I get the error.
```
# go get github.com/binance-chain/bsc 

go: downloading github.com/binance-chain/bsc v1.0.7
go get: github.com/binance-chain/bsc@none updating to
        github.com/binance-chain/bsc@v1.0.7: parsing go.mod:
        module declares its path as: github.com/ethereum/go-ethereum
                but was required as: github.com/binance-chain/bsc
```

Anyone can help me, please?
Thanks in advance.

**Comment by onemedicine** [comment]
Seems to be a common error：import cycle not allowed, because the bsc project still uses "module github.com/ethereum/go-ethereum" and it import this "github.com/ethereum/go-ethereum" . Don't worry about it, you can use that real ethereum, but pay attention to the "params.ChainConfig".
Good luck to you!

**Comment by guagualvcha** [comment]
try use  replace in go.mod `https://golang.org/doc/modules/gomod-ref#replace`

**Comment by 0pa9ue** [comment]
Is there any way that can solve this problem? I'm still facing the same error.
