### ISSUE TITLE
Is it safe to delete chaindata/ancient in fast sync mode to free up disk space? 

### ISSUE THREAD

**Issue by maldo-ctrl** [binance-chain/bsc#316]
Hi!
My `chaindata/ancient` is now around the 250gb. I would like to know if it's possible to empty that folder to free up some disk space when running a bsc node in fast sync mode. I have read that in geth it's possible, but I just wanted to check before trashing my node.

Thanks!

**Comment by zhongfu** [comment]
> I would like to know if it's possible to empty [`chaindata/ancient`] to free up some disk space when running a bsc node in fast sync mode.

*technically* it's possible... **but** i wouldn't do it, since geth will just refuse to start up if your `ancient` folder is damaged or corrupt

> I have read that in geth it's possible, but I just wanted to check before trashing my node.

i'd be interested to know where you read that, because you would indeed have trashed your node if you did that

in any case -- if you're desperate for disk space, you can move your `chaindata/ancient` folder elsewhere (spinning rust might work too, i think) and let geth know where it is:
- by adding `--datadir.ancient=/path/to/ancient` to your startup command, **or**
- by adding `DatabaseFreezer = /path/to/ancient` under the `Eth` section in your config file

**Comment by maldo-ctrl** [comment]
Thank you very much, that's exactly what I needed :D
