### ISSUE TITLE
Public RPC node requests fail > 80% of the time, trend increasing.

### ISSUE THREAD

**Issue by Strernd** [binance-chain/bsc#612]
On a weekly basis I extract logs from a smart contract. Per week it's usually below 500 log events.

While I'm able to do this on ETH and MATIC nodes in about 0.5 seconds (just query the whole block range and it **just works**), it takes an hour on any public Binance Smart Chain RPC node (bsc-dataseed.binance.org).

The block range limit is 5000, that's ok, so I'm chunking and making multiple requests. But the requests take ~10 seconds and in 80% of the time **they just fail**. I built a retry handler to execute the same request over and over again until it returns a valid result. In a lot of cases there are 5+ tries necessary (each taking 10 seconds) to get a result for the logs. 

I'm also observing an alarming trend: 3-4 weeks ago a retry limit of 5 was sufficient, now I'm already up to 10+ because the request fail rate more than doubled. At this speed public nodes ( so Metamask etc. as well) will not be usable anymore by the beginning of the next year, when a request will take 30 tries to return valid data.

Seriously, judging by the amount of new issued regarding node sync and hardware requirement you have a massive problem. 
Not even the official Binance team is capable of running this time bomb by themselves.

**Comment by guagualvcha** [comment]
@Strernd  Exact logs is a heavy query,  the block range limit is 5000, if you query the un-cached blocks, it has to load all block headers, compare with bloom filter && decode receipts, as BSC get much larger blocks size compared to ETH and MATIC, it definitely needs more time to serve the requests.  A reasonable way for you is to try query with a block range 1000 or 500 rather than retry.  The dev is working on using a centralized database to index logs and serve requests like what infura does, this will take a while.  The title is exaggerating the fact, only the heavy requests with specified params will do.

**Comment by BinanceG11** [comment]
Please join us at Discord, #node-support subchannel for more discussion https://discord.com/invite/YPDsUqcwR8

**Comment by BinanceG11** [comment]
We have responded to the question and will proceed to close the case as we didn't get any additional question after 3days.  Please proceed to join our Discord channel for more discussion at https://discord.com/invite/YPDsUqcwR8
