### ISSUE TITLE
How do you Raid your NVMe?

### ISSUE THREAD

**Issue by edgeofthegame** [binance-chain/bsc#621]
I guess many nodes are located on NVMe raids now. I am using ubuntu 20, and my server manager created **LVM** of a few NVMe. But when I read about ubuntu raid zero, most of articles suggest using **MDADM** instead

What method you think is preferable? 
Thank you.

**Comment by m-e-r-k-l-e-root** [comment]
This question is covered in nearly every Linux beginner tutorial. Use google.

**Comment by edgeofthegame** [comment]
Obviously, since I know the words **MDADM** and **LVM** , I googled a few articles about the issue (about ten articles, to be precised), and there were some comparisons of these words, and even some performance tests, but none of those tests were connected anyhow to bsc (or any other blockchain) performance, sorry.

What is the motivation of people like you to leave a comment like that, anyway? Do you have a pay per comment job or something?

**Comment by ascunha** [comment]
> Obviously, since I know the words **MDADM** and **LVM** , I googled a few articles about the issue (about ten articles, to be precised), and there were some comparisons of these words, and even some performance tests, but none of those tests were connected anyhow to bsc (or any other blockchain) performance, sorry.
> 
> What is the motivation of people like you to leave a comment like that, anyway? Do you have a pay per comment job or something?

lvm uses md for raid afaik, but without knowing what and why your sysadmin (im assuming server manager is a person not a software lol) did it is kind of hard to guess, I suggest you ask him to explain better.
If you just used lvm to get a bigger volume without raid then yeah, no need to compare, you are not doing raid. 

Honestly, I understand m-e-r-k-l-e-root frustration here, you should not think of it as a personal attack... some are getting frustrated (include me) with the turn the issues section took. There are really a lot of questions about basic system setup and administration, lots of suggestions that don't seem very right, etc... 
You should probably clarify whats going on with your server and benchmark/monitor it yourself to have an idea of whats better, whats not working and so on. 

good luck.

**Comment by MevDaddy** [comment]
“but none of those tests were connected anyhow to bsc (or any other blockchain) performance, sorry.”

Do performance tests & benchmarking on your own then come to your own conclusions. That’s how everyone else does it if they can’t find the question they’re looking for… You can’t just rely on other people to do all the work for you. @m-e-r-k-l-e-root is right, the BSC issues tab is starting to feel like [https://askubuntu.com/](AskUbuntu) or [https://stackoverflow.com/](Stackoverflow), very frustrating. I feel bad for @guagualvcha he’s literally answered so many questions that are answered on page 1 of any beginner Linux book.

**Comment by edgeofthegame** [comment]
Do you think that BSC issues tab is starting to feel like AskUbuntu or Stackoverflow because your customers are stupid? I do not think that I am so stupid. I think that maybe your software is not working very well. And I do not remember I asked any of you to do any work for me. I just ask what method is preferable. If you do not know or do not want to tell, it is totally OK, you could have just kept silence. But instead you come here and start telling me how stupid I am.

**Comment by MevDaddy** [comment]
> Do you think that BSC issues tab is starting to feel like AskUbuntu or Stackoverflow because your customers are stupid? I do not think that I am so stupid. I think that maybe your software is not working very well. And I do not remember I asked any of you to do any work for me. I just ask what method is preferable. If you do not know or do not want to tell, it is totally OK, you could have just kept silence. But instead you come here and start telling me how stupid I am.

If you did some research to understand what RAID is and or how it actually works you’d understand why your question is ridiculous. You literally asked if LVM or MDADM is preferable 🤦‍♂️ Follow @ascunha’s advice:

“You should probably clarify whats going on with your server and benchmark/monitor it yourself to have an idea of whats better, whats not working and so on.”

**Comment by guagualvcha** [comment]
Some detailed tutorial from community: https://telegra.ph/Not-best-practice-of-running-a-BSC-Validator-11-29

**Comment by miohtama** [comment]
Here are my RAID0 instructions:

https://tradingstrategy.ai/blog/preparing-a-server-for-hosting-goethereum-full-node

You need RAID0, preferably more than 2 disks, as RAID0 on 2 NVMe disks still has issue of getting the node synced.

**Comment by edgeofthegame** [comment]
Thank you. I will try raid0 with 4nvme

**Comment by MevDaddy** [comment]
> And I do not remember I asked any of you to do any work for me.

Yes you did, you wanted people to give you a step by step tutorial on how to create a RAID using multiple storage devices being that you are incapable of figuring it out on your own and/or it’s too hard for you to do your own research.

> Obviously, since I know the words MDADM and LVM

🤦‍♂️ You know the words “LVM” & “MDADM” so what? Do you feel proud? You think you deserve an award or something? You have no idea what either of them mean of which is why you asked this moronic braindead question in the first place.

> Do you think that BSC issues tab is starting to feel like AskUbuntu or Stackoverflow because your customers are stupid?

When it comes to people like you, absolutely 100% yes. I mean just look at your post history you’re completely clueless. You never have the slightest clue as to what you’re talking about and just expect everyone else to do all the work for you and answer all your questions without you ever figuring anything out on your own, you should be embarrassed.

> but none of those tests were connected anyhow to bsc (or any other blockchain) performance, sorry.

Ok? So someone else didn’t do all the work for you (I.e performance tests) therefore you can’t do it on your own? You require others to literally spoon feed you answers like a child. 

Finally, the answers @guagualvcha & @miohtama offered can be found on the very first page of Google when searching for anything along the lines of “how to RAID block devices on Linux”, did you REALLY need them to spoon feed you beginner level Linux step by step guides because Google is too hard for you to use?

Thanks for contributing to the major degradation of the BSC issues tab… 

One last thing, you should get this book:

![97EDDDAD-0651-4AE4-9EDD-7016AD4D2591](https://user-images.githubusercontent.com/94683590/144682249-1ee1ac90-35cf-43dc-86cb-df305a581d8e.jpeg)

Being that your mental capacity seems to be that of a child and that I’ve seen literal 12 year olds with more knowledge in regard to how Linux works than you, I really think the book I’ve mentioned above will help you.

I’m done here, the BSC repo has become a complete joke. The fact people are actually answering these questions just makes the problem worse, it incentivizes more low quality questions like this to be asked.

**Comment by edgeofthegame** [comment]
> Here are my RAID0 instructions:
> 
> https://tradingstrategy.ai/blog/preparing-a-server-for-hosting-goethereum-full-node
> 
> You need RAID0, preferably more than 2 disks, as RAID0 on 2 NVMe disks still has issue of getting the node synced.

Okay I followed your instrucions, and made RAID0 on 4 NVMe x 2T disks, just to be sure. Also I made MaxPeers = 100 and cache = 16000, diffsync, etc. Sync from snapshot was kinda fast (a few hours), but right now node is displaying frequent reorgs (a few reorgs every min), and always 8-16 seconds late.
