### ISSUE TITLE
do light process err at block            num=13,552,469 err="account storage root mismatch"

### ISSUE THREAD

**Issue by masayil** [binance-chain/bsc#672]
get error "account storage root mismatch" when using diffsync
Does it affect  the data? Or it is normal?

**Comment by KeefeL** [comment]
It's normal, just ignore it.

**Comment by np-wauxhall** [comment]
Hello, faced it too, so why is it a error if it's normal, maybe it's a waning then?

**Comment by KeefeL** [comment]
> Hello, faced it too, so why is it a error if it's normal, maybe it's a waning then?

Well, it is caused by a bug introduced in the first release of diffsync, and has been fixed in release 1.1.7, while there are some p2p nodes have not upgraded to 1.1.7 version, when you run diffsync, you may receive data from those nodes and then may occur this error, but if your node is running binary 1.1.7, you can just ignore it. When all nodes have upgraded to 1.1.7 or later version, this error are not expected to happen again, so I think this should be an error, not a warning.

**Comment by np-wauxhall** [comment]
Got it, thank you very much for explanation!
