### ISSUE TITLE
BEP-20 token tx issue.

### ISSUE THREAD

**Issue by kwnm** [binance-chain/bsc#701]
BEP-20 token tx failed and token transfered to pancakeswap LP.
Let me know the reason and how to solve. 

https://bscscan.com/tx/0x20d82e0cd618bc20fb9e7c9e83bb5faca35be300b58c78c7d72a159c2d831e17

Thanks.

**Comment by Zaczero** [comment]
I see nothing wrong with the transaction you have provided (swap completed successfully and everybody received their funds). It looks like the 'from' address belongs to some sort of exchange/pool so I believe you should contact their support instead as this issue seems to be unrelated to the bsc node client.

**Comment by guagualvcha** [comment]
The tx looks fine, will close this issue.
