### ISSUE TITLE
Can i run fullnode with account?

### ISSUE THREAD

**Issue by kugimiya530** [binance-chain/bsc#706]
i already make my fullnode work

i want to share it to my friend

how to make they connect my node need account  if yes  how to create

another question  can i  check who connect to my fullnode?

**Comment by Zaczero** [comment]
> ## i want to share it to my friend

I suppose you are talking about the RPC (in-MetaMask connectivity etc.).

There are two ways the RPC can connect: via HTTP or WebSocket. The HTTP is more compatible but slower when you send multiple requests over a short period of time. However, it is quicker to establish the connection and send just 1 or 2 requests. So my answer will address the HTTP RPC setup.

In your `config.toml` file there are 4 related entries under the `[Node]` section: `HTTPHost`, `HTTPPort`, `HTTPVirtualHosts` and `HTTPModules`.

At first, since you are willing to share your RPC, set `HTTPHost = "0.0.0.0"`. This will bind the socket publicly so that people from outside your server can connect to it. Be warned; bots constantly scan the internet for publicly open RPC servers and will most likely make use of that. Nothing terrible will happen, but you will provide your processing power for free.

Secondly, set `HTTPPort` to your will. The default value is `HTTPPort = 8545`. It's the port on which the socket will be open. If you set it to something non-standard from the possible range of 1024-49151 (non-root ports), it will increase the amount of time required for your server to be indexed by bots.

Thirdly, set `HTTPVirtualHosts` to `HTTPVirtualHosts = ["*"]` since your setup will probably not involve any purchased domains. Otherwise, you would set it to something like `HTTPVirtualHosts = ["mydomain.com"]`. It's a basic setting (applicable only when you own a domain) to ensure that the client connecting does it with the use of your domain. For example, an IP-direct connection will not work.

Finally, set `HTTPModules` to enable only the minimum modules you need. The default is `HTTPModules = ["eth", "net", "web3", "txpool", "parlia"]`. Most of the time just `HTTPModules = ["eth", "net", "web3"]` is enough. You can browse what each module is responsible for at https://geth.ethereum.org/docs/rpc/server (partial list).

Having everything set, restart the node and check whether the connection is working:

1. Run `ss -tlp | grep geth` to validate that your server is listening on the port you specified. You should spot something like: `*:HTTPPort` (e.g. `*:8545`) in the output. If the output is empty, the node failed to start (or is still starting), so you should check your `node.log` for more information.

2. Now, ensure that no firewall is blocking your connection. You can use some external tool to validate that your port is accessible from the outside. For example, https://portchecker.co/. Just enter the IP address of your server and the port specified (`HTTPPort`). You should see a message like `Port HTTPPort is open.`. Otherwise, you will have to update your firewall rules.

3. Now, you can validate whether your RPC is working in the application of choice (e.g., MetaMask). Your RPC URL is the following: `http://SERVER_IP:HTTPPort/`.

And that's it. Done.

---

Final words.

This configuration, while easy to do, will not encrypt your connection. It's a great first step just to get started, but you should think about setting up a proper `HTTPS` connectivity at one point. For that, you could use `nginx` and `proxy_pass` the connection to the RPC server, which should be listening on just `localhost` (no external connectivity). However, I will not instruct you how to do it here as it would have taken at least ten more paragraphs, and there already exist content-rich resources on that topic. Just a heads-up: you will need to purchase a domain for that. You can use `Let's Encrypt` and `certbot` to acquire a free `HTTPS` certificate - there is no need to pay for those.

> ## how to make they connect my node need account if yes how to create

There does not exist any natively-supported RPC auth system. However, here are the two most common ways of managing access.

1. IP whitelist, this can be configured on your firewall level. Simply whitelist the IP addresses which are allowed to your RPC server.

2. In-URL authentication string like http://SERVER_IP:PORT/691890143708613961398. For that, you would need to have a proper web server installed - `nginx` will do. I assume you will manage the authentication tokens manually as it's the simplest way to share your server with just a few people. So, in your host configuration, just guard the `proxy_pass` inside the `location /691890143708613961398 { ... }` section. And if you want to have, let's say, two distinct authentication strings, simply duplicate the `location` with different paths assigned to them.

> ## another question can i check who connect to my fullnode?

I am not aware _(have not really looked much into it - could be wrong)_ whether there exists a built-in logging system exists for RPC connections. However, with the `nginx` setup, by default, there will be an `/var/log/nginx/access.log` file with all the connections made to your server. This should satisfy your needs.

**Comment by ya9iz** [comment]
can you give an example ho to whitelist IPs with ufw in linux?

**Comment by Zaczero** [comment]
@ya9iz

`ufw allow from 123.123.123.123 to any port 8545`

- `123.123.123.123` replace with the whitelisted IP address.
- `8545` replace with the RPC port number.

---

To delete the whitelist:

1. `ufw status numbered` - this will print out all the ufw rules with unique numbers assigned to them.
2. `ufw delete X` - this will delete the rule with the `X` number from the above command.

**Comment by kugimiya530** [comment]
> 

Hi very appreciate i am new for linux
can u release some detail 
for this one
![image](https://user-images.githubusercontent.com/30725599/148710596-297e917d-df3a-4eaa-8af3-d204f7afa908.png)

**Comment by Zaczero** [comment]
@kugimiya530 

`nginx` documentation and web search are your friends.

* https://nginx.org/en/docs/beginners_guide.html
* https://nginx.org/en/docs/http/ngx_http_proxy_module.html#proxy_pass
* https://www.nginx.com/resources/wiki/start/topics/recipes/geth/

Your final configuration will contain something like this:

```conf
location /MY_AUTH_STRING_1 {
    proxy_pass   http://127.0.0.1:8545/;
}

location /MY_AUTH_STRING_2 {
    proxy_pass    http://127.0.0.1:8545/;
}
```

The `proxy_set_header` which you may find in some resources is not mandatory in our case. Some resources also use the following way of matching URLs: `location ^~ /...`. The difference between `^~` and _nothing_ is that _nothing_ will use native match while `~` means that regex is used which is a little bit slower. Both will work but in terms of maximizing performance, the snippet of code pasted above will be faster in your scenario. Here you can learn more on that topic: https://nginx.org/en/docs/http/ngx_http_core_module.html#location.

Also, once the `nginx` setup is complete, edit your `HTTPHost = "127.0.0.1"` to disable external connectivity with your RPC server (you will be connecting to it 'internally' via `nginx`):

`CLIENT --(http://PUBLIC_IP:PORT/)--> NGINX --(http://127.0.0.1:8545/)--> RPC`

**Comment by kugimiya530** [comment]
> @kugimiya530
> 
> `nginx` documentation and web search are your friends.
> 
> * https://nginx.org/en/docs/beginners_guide.html
> * https://nginx.org/en/docs/http/ngx_http_proxy_module.html#proxy_pass
> * https://www.nginx.com/resources/wiki/start/topics/recipes/geth/
> 
> Your final configuration will contain something like this:
> 
> ```
> location /MY_AUTH_STRING_1 {
>     proxy_pass   http://127.0.0.1:8545/;
> }
> 
> location /MY_AUTH_STRING_2 {
>     proxy_pass    http://127.0.0.1:8545/;
> }
> ```
> 
> The `proxy_set_header` which you may find in some resources is not mandatory in our case. Some resources also use the following way of matching URLs: `location ^~ /...`. The difference between `^~` and _nothing_ is that _nothing_ will use native match while `~` means that regex is used which is a little bit slower. Both will work but in terms of maximizing performance, the snippet of code pasted above will be faster in your scenario. Here you can learn more on that topic: https://nginx.org/en/docs/http/ngx_http_core_module.html#location.
> 
> Also, once the `nginx` setup is complete, edit your `HTTPHost = "127.0.0.1"` to disable external connectivity with your RPC server (you will be connecting to it 'internally' via `nginx`):
> 
> `CLIENT --(http://PUBLIC_IP:PORT/)--> NGINX --(http://127.0.0.1:8545/)--> RPC`

Love here
always find the answer
okay
i will take some time to study it, thx very much~

**Comment by kugimiya530** [comment]
> @kugimiya530
> 
> `nginx` documentation and web search are your friends.
> 
> * https://nginx.org/en/docs/beginners_guide.html
> * https://nginx.org/en/docs/http/ngx_http_proxy_module.html#proxy_pass
> * https://www.nginx.com/resources/wiki/start/topics/recipes/geth/
> 
> Your final configuration will contain something like this:
> 
> ```
> location /MY_AUTH_STRING_1 {
>     proxy_pass   http://127.0.0.1:8545/;
> }
> 
> location /MY_AUTH_STRING_2 {
>     proxy_pass    http://127.0.0.1:8545/;
> }
> ```
> 
> The `proxy_set_header` which you may find in some resources is not mandatory in our case. Some resources also use the following way of matching URLs: `location ^~ /...`. The difference between `^~` and _nothing_ is that _nothing_ will use native match while `~` means that regex is used which is a little bit slower. Both will work but in terms of maximizing performance, the snippet of code pasted above will be faster in your scenario. Here you can learn more on that topic: https://nginx.org/en/docs/http/ngx_http_core_module.html#location.
> 
> Also, once the `nginx` setup is complete, edit your `HTTPHost = "127.0.0.1"` to disable external connectivity with your RPC server (you will be connecting to it 'internally' via `nginx`):
> 
> `CLIENT --(http://PUBLIC_IP:PORT/)--> NGINX --(http://127.0.0.1:8545/)--> RPC`

Hi thx for you help
it's very helpful
i am finish auth_string part

did u know how to redirect to "ws://localhost" ?
cuz it's will show "nginx: [emerg] invalid URL prefix" 
i want to redirect websocket port like http do

**Comment by Zaczero** [comment]
@kugimiya530 

```conf
location / {
    proxy_pass http://localhost:8546;
    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection $http_upgrade;
}
```

WebSocket is an *upgraded* HTTP connection thus all you need is to proxy the HTTP with some additional headers: `Upgrade` and `Connection`. In my example, `8546` is the port of the WS RPC server. I am unsure whether you need the `proxy_http_version` line, feel free to test without it.

**Comment by kugimiya530** [comment]
> @kugimiya530
> 
> ```
> location / {
>     proxy_pass http://localhost:8546;
>     proxy_http_version 1.1;
>     proxy_set_header Upgrade $http_upgrade;
>     proxy_set_header Connection $http_upgrade;
> }
> ```
> 
> WebSocket is an _upgraded_ HTTP connection thus all you need is to proxy the HTTP with some additional headers: `Upgrade` and `Connection`. In my example, `8546` is the port of the WS RPC server. I am unsure whether you need the `proxy_http_version` line, feel free to test without it.

First of all, thx for your kindly help

I have 2 question

Q1
in my example my nginx will run /etc/nginx/conf.d     inside all conf, can I limit each conf 's  "IP quantity" in one time, i am not mean each "IP's connection quantity"   

Q2
my fullnode always behind 60~100 blocks and i don't know why, that's struggle me alot
my server spec
24C 48T  256GB RAM  and  4565MB/sec  NVME
and it's still 2.5TB  space available
![image](https://user-images.githubusercontent.com/30725599/149247645-62474f48-dc96-4844-9cb2-b01eeafda83c.png)

**Comment by Zaczero** [comment]
@kugimiya530 

## Q1:

It sounds like you are talking about the `limit_conn` directive. It basically limits how many parallel connections can be made from a single IP address at a time. https://nginx.org/en/docs/http/ngx_http_limit_conn_module.html

You may also be interested in exploring nginx's rate-limiting `limit_req` (how many requests per second can be made).  
https://www.freecodecamp.org/news/nginx-rate-limiting-in-a-nutshell-128fe9e0126c/  
https://www.nginx.com/blog/rate-limiting-nginx/

## Q2:

I have seen quite many people having the same issue as you in here. One of the most recent threads: https://github.com/binance-chain/bsc/issues/707. I will quote my response below:

> I remember having the same issue. What I did, in the end, was to trash the data and set up a completely fresh node using the snapshot provided by the BSC team: https://github.com/binance-chain/bsc-snapshots. Of course, it's not an ideal solution, but that's what helped in my case.

**Comment by kugimiya530** [comment]
> @kugimiya530
> 
> ## Q1:
> It sounds like you are talking about the `limit_conn` directive. It basically limits how many parallel connections can be made from a single IP address at a time. https://nginx.org/en/docs/http/ngx_http_limit_conn_module.html
> 
> You may also be interested in exploring nginx's rate-limiting `limit_req` (how many requests per second can be made). https://www.freecodecamp.org/news/nginx-rate-limiting-in-a-nutshell-128fe9e0126c/ https://www.nginx.com/blog/rate-limiting-nginx/
> 
> ## Q2:
> I have seen quite many people having the same issue as you in here. One of the most recent threads: #707. I will quote my response below:
> 
> > I remember having the same issue. What I did, in the end, was to trash the data and set up a completely fresh node using the snapshot provided by the BSC team: https://github.com/binance-chain/bsc-snapshots. Of course, it's not an ideal solution, but that's what helped in my case.

for the Q1 
no i am not searching for  these command , cuz i want to  limit  "IP Quantity for that conf"
                                                                                        not          "Each IP's connections"
 So i guess there is no this function for nginx  i  did  search already :(


For Q2
I am using vultr Bare-metal  cloud server
i try to download snapshot like 3~4 times   always failed,thats why i syncing from genesis block

maybe that's why i always behind 100blocks?
and i can connect to my RPC but it's didn't update my wallet information

by the way thx for your suggestion i will download snapshot again

**Comment by Zaczero** [comment]
@kugimiya530 

## Q1

Maybe do the following: limit_conn to 1 per IP + limit_conn to 3 per server.  
This section will help you:

![image](https://user-images.githubusercontent.com/10835147/149279938-3ec21512-535a-46e1-96e2-f8cd1646763b.png)

Reference: https://nginx.org/en/docs/http/ngx_http_limit_conn_module.html#limit_conn

## and can i know you parameter for running node?

This will make no difference. I use mostly default parameters and changing anything here will not help you - I tried. As said, I had the same issue once :-).

**Comment by kugimiya530** [comment]
> @kugimiya530
> 
> ## 问题 1
> 可以执行以下操作：每个 IP limit_conn 到 1 个 + limit_conn 到每个服务器 3 个。本节将帮助您：
> 
> ![image](https://user-images.githubusercontent.com/10835147/149279938-3ec21512-535a-46e1-96e2-f8cd1646763b.png)
> 
> 参考资料： https://nginx.org/en/docs/http/ngx_http_limit_conn_module.html#limit_conn
> 
> ## 我能知道你运行节点的参数吗？
> 这不会有任何区别。我主要使用默认参数，在这里更改任何内容都不会帮助你 - 我试过了。正如所说，我曾经遇到过同样的问题：-）。

for Q1 it's still not match what i want
but it's ok  nvm

for Q2  i just downloaded  snapshot and try to sync for a fresh new fullnode  , just need to wait

and



server {

  listen 80;
  listen [::]:80;
  server_name localhost;

  location ^~ /ws {
      proxy_http_version 1.1;
      proxy_set_header Upgrade $http_upgrade;
      proxy_set_header Connection "upgrade";
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header Host $http_host;
      proxy_set_header X-NginX-Proxy true;
      proxy_pass   http://127.0.0.1:8546/;
  }

  location ^~ /rpc {
      proxy_http_version 1.1;
      proxy_set_header Upgrade $http_upgrade;
      proxy_set_header Connection "upgrade";
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header Host $http_host;
      proxy_set_header X-NginX-Proxy true;
      proxy_pass    http://127.0.0.1:8545/;
  }
}

for this example   i want to log,every connection  so  i modify to 


server {

  listen 666;
  listen [::]:666;
  server_name localhost;

  location ^~ /w {
**access_log  /etc/nginx/log/Maiko.access.log maiko;**
      proxy_http_version 1.1;
      proxy_set_header Upgrade $http_upgrade;
      proxy_set_header Connection "upgrade";
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header Host $http_host;
      proxy_set_header X-NginX-Proxy true;
      proxy_pass   http://127.0.0.1:9999/;
  }

  location ^~ /h {
**access_log  /etc/nginx/log/Maiko.access.log maiko;**
      proxy_http_version 1.1;
      proxy_set_header Upgrade $http_upgrade;
      proxy_set_header Connection "upgrade";
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header Host $http_host;
      proxy_set_header X-NginX-Proxy true;
      proxy_pass    http://127.0.0.1:6666/;
  }
}

why there is only /h connection got record   /w  not
/h for http rpc   /w for websocket

**Comment by Zaczero** [comment]
@kugimiya530

## Q1-new

That's my setup for the `access_log` which works fine:

Inside `nginx.conf` -> `http { ... }`:

```conf
log_format vhost_combined '$server_name $remote_addr - $remote_user [$time_local] "$request_method $scheme://$host$request_uri $server_protocol" $status $body_bytes_sent "$http_referer" "$http_user_agent"';

access_log /var/log/nginx/access.log vhost_combined;
```

Remove all other `access_log` entries to prevent potential conflicts.

## Q2

I would suggest checking your `access.log` for failed requests. It is possible that the service you have mentioned does not support RPC addresses with path-based authorization. Example:

![image](https://user-images.githubusercontent.com/10835147/149486463-302af36e-f94e-44e2-bbd5-0599c49a0fe0.png)
