### ISSUE TITLE
BSC releases should include binaries for Linux ARM platform

### ISSUE THREAD

**Issue by terianil** [binance-chain/bsc#712]
# Rationale

There are many cost efficient ARM instances at AWS (like Is4gen.xlarge, Im4gn.2xlarge) that could be a good way to host full BSC nodes. ARM builds are also officially available in go-ethereum (as well as in many go-ethereum forks).

**Comment by kyrie-yl** [comment]
nice advice. we will include it from next version.

**Comment by mattwhelpley** [comment]
You can compile it yourself pretty quickly. [Instead of downloading golang on the first step from this guide](https://www.quicknode.com/guides/infrastructure/how-to-run-a-binance-smart-chain-node
), do the following as ec2-user:

sudo yum-config-manager --enable epel
sudo amazon-linux-extras install epel -y
sudo yum install golang -y

That'll get you the libraries necessary to compile geth from scratch and you can run with it from there.
