### ISSUE TITLE
"Not allowed to propose block"    err="unauthorized validator"

### ISSUE THREAD

**Issue by silsuer** [binance-chain/bsc#718]
when i use miner.start() , the bsc.log show:  "Not allowed to propose block"           err="unauthorized validator"

how can i fix it ?

geth command line : ./geth --syncmode fast --datadir ./node --config ./config.toml --cache 40960 --http --http.addr "0.0.0.0" --http.vhosts '*'  --http.api eth,net,web3,personal,debug,miner --ws --ws.addr "0.0.0.0" --ws.origins '*'  --ws.api eth,net,web3  --rpc --rpcaddr "0.0.0.0"  --rpc.allow-unprotected-txs -txlookuplimit 0 --rpc.allow-unprotected-txs --allow-insecure-unlock --unlock "0xxxxxxxx my address" --password "/path/to/pass.txt"

**Comment by Zaczero** [comment]
BSC is a PoS system. The PoW miner won't work here. In order to become a validator, you must be one of the TOP 21 most-funded validators - it's no easy task :).
Currently, you need **at least** `787,943.602549 BNB` *(self-stake + delegator-stake)*.

You are most likely going to stake your funds instead *(become a delegator)*. Useful links:

https://academy.binance.com/en/articles/a-quick-guide-to-bnb-staking-on-binance-smart-chain-bsc

https://binance-wallet.gitbook.io/binance-chain-wallet/bew-guides/beginers-guide/binance-chain-staking/how-to-delegate-your-bnb-with-binance-extension-wallet

**Comment by silsuer** [comment]
oh my god...   I want to be the first tx after an  add Liquidity Transaction.  What should I do ? Only the same gas ，That's hard to do it

**Comment by Zaczero** [comment]
@silsuer You can write a smart contract to execute both `add liquidity` and `something else` at the same time. Alternatively, you can write a script that would broadcast both transactions with very little delay in between but this will not guarantee what you want to achieve. Smart contract would be the only reliable and cheap way of doing it.

**Comment by HungChu** [comment]
I built my local bsc network with 3 nodes. After that I run 4th node:
./build/bin/geth --identity "node4"  --datadir node4 --networkid 332211 --allow-insecure-unlock --nat extip:0.0.0.0 --port 30306 --http --rpcaddr "0.0.0.0" --rpcport 9548 --rpcapi="personal,debug,eth,net,web3,txpool,parlia" --rpccorsdomain "*" --rpcvhosts "*" --syncmode 'full' --mine --miner.threads=1 --miner.etherbase="0x" --unlock 0x --password password.txt
then i got exactly this error.
Please give me an advice to fix it
