### ISSUE TITLE
offline block prune tools

### ISSUE THREAD

**Issue by masayil** [binance-chain/bsc#744]
Suppose the current block height is 100000.
After I run the cmd : `./geth snapshot prune-block --datadir ./node --datadir.ancient ./chaindata/ancient --block-amount-reserved 9000 --triesInMemory 32 --check-snapshot-with-mpt` , I will not be able to query data before 9000.  In other words, this command delete block 0-9000  data.
Is that correct?

**Comment by DefiDebauchery** [comment]
No, `block-amount-reserved` would be how many you wanted to keep - so if you had block height of 100,000 (and assuming you'd never run the command before), theoretically it would be blocks 91000 - 100000

However, reading the PR, is _seems_ that this only operates on blocks that have been stored in `ancient`. If the freezer follows Ethereum's handling, that's 3 "epochs" (* 30,000 blocks per epoch = 90,000 total blocks, which is ~3.125 days in BSC), so maybe you'd have 90,000 + remaining ancient blocks?

Maybe @Mercybudda would be willing to clear that up.

**Comment by Mercybudda** [comment]
@masayil
Hi, in your case, 9000 doesn't mean you prune amount of 9000 blocks, it means it will only keep the last 9000 amount of blocks in `ancientDB`. For example, if the blockNumber in your `ancientDB` looks like this [0, 1, 2 ... 19000], after you run your command, it will be [10001, 10002 ... 19000], i.e. only reserved the last 9000 blocks, that's why you are not able to query data before 9000. Please let me know if you have any other questions.
