### ISSUE TITLE
config.toml in v1.0.6 is invalid

### ISSUE THREAD

**Issue by swissbitX** [binance-chain/bsc#86]
The mainnet.zip in release 1.0.6 has a invalid config.toml

https://github.com/binance-chain/bsc/releases/tag/v1.0.6

In config.toml under `MaxMessageSize` there is a "S", which leads to an error while starting geth.

```
[Shh]
MaxMessageSize = 1048576S
RestrictConnectionBetweenLightClients = true
```

**Comment by xqpoo9** [comment]
I'm having the same issue, "Fatal: ./config.toml, line 43: invalid TOML syntax" on the same release preventing from being able to start with geth --config ./config.toml --datadir ./node --pprofaddr 0.0.0.0 --metrics --pprof

**Comment by meetsiraja** [comment]
Which one is the stable version to run BSC Full node?

**Comment by guagualvcha** [comment]
Thanks for report this. The config file is fixed now, please download again.

**Comment by chrisfranko** [comment]
why do you need to use the config while when you could just make it the default?

**Comment by chrisfranko** [comment]
If you need an experience developer to help you launch your node the right way, I got you.

**Comment by xqpoo9** [comment]
@guagualvcha 

Thank you, that fixes line 43 error. There's still a couple more when following the[ bsc fullnode install commands](https://docs.binance.org/smart-chain/developer/fullnode.html) on linux:

Fatal: ./config.toml, line 52: field 'GraphQLPort' is not defined in node.Config, see https://godoc.org/github.com/ethereum/go-ethereum/node#Config for available fields

Fatal: ./config.toml, line 68: field 'LogConfig' is not defined in node.Config, see https://godoc.org/github.com/ethereum/go-ethereum/node#Config for available fields

I'm currently commenting those lines out of the config in order to get it running. Command below:

    wget --no-check-certificate  $(curl -s https://api.github.com/repos/binance-chain/bsc/releases/latest |grep browser_ |grep mainnet |cut -d\" -f4)
    unzip mainnet.zip
    geth --datadir node init genesis.json
    geth --config ./config.toml --datadir ./node --pprofaddr 0.0.0.0 --metrics --pprof
